common: &common
  keywords: "key"
  description: "desc"
  author: "Rique Li, hi@liwei.me"
  site_title: "More App"
  admin_key: iamhere
  admin_account: liwei
  admin_password: liwei
  default_icon_path: /images/sample_icon.png
  categories: ["Lifestyle", "Movie", "Book", "Other"]
  each_show: 6
development:
  <<: *common

test:
  <<: *common  

production:
  <<: *common
